/*
 * This file is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file    Pico2/c1_main.c
 * @brief   RP2350 core1 entry point for ArduPilot ChibiOS SMP.
 *
 * The _crt0_c1_entry trampoline (generated by crt0_v8m-ml.S when
 * CRT0_EXTRA_CORES_NUMBER >= 1) sets up core1's MSP/PSP stacks, enables the
 * FPU, and then calls this function.
 *
 * The key synchronisation rule from the ChibiOS SMP model:
 *   - Core1 must NOT call chInstanceObjectInit() until core0 has set
 *     ch_system.state = ch_sys_running (done at the end of chSysInit()).
 *   - chSysWaitSystemState(ch_sys_running) busy-waits on that flag.
 *
 * Once initialised, core1 enters the idle loop exactly as the ChibiOS demo
 * does — the real work happens in threads pinned to core1 by
 * thread_create_alloc_on_core() in Scheduler.cpp.
 */

#include "ch.h"
#include "hal.h"

#if CH_CFG_SMP_MODE == TRUE && PORT_CORES_NUMBER > 1

/*
 * Stage canary: written sequentially by each milestone in core1's boot.
 * Read via GDB/OpenOCD after halt to see how far core1 got:
 *   0 = never reached __c1_cpu_init (crashed in very early CRT0 setup)
 *   1 = __c1_cpu_init ran (VTOR/FPU/stacks are set up, CONTROL not yet switched)
 *   2 = __c1_late_init ran (CONTROL=PSP, stacks filled, about to call c1_main)
 *   3 = c1_main entered (before chSysWaitSystemState)
 *   4 = chSysWaitSystemState returned (state==ch_sys_running seen)
 *   0x4A = chInstanceObjectInit returned (c1_inst_stage=0x48 was last written)
 *   0x4B = about to call chSysUnlock
 *   0x4C = chSysUnlock returned (IRQs now fully live on core1)
 *   0x4D = idle loop body entered (first port_wait_for_interrupt)
 *   5 = (legacy — now superseded by 0x4A..0x4D sub-stages above)
 *   6 = (legacy — now superseded by 0x4D)
 *
 * Also check c1_inst_stage (defined in chinstances.c) for sub-step within
 * chInstanceObjectInit:
 *   0x40 = entered, about to call port_init
 *   0x41 = port_init returned
 *   0x42 = ch_pqueue_init returned (rlist ready)
 *   0x43 = __vt_object_init returned (vtlist ready)
 *   0x44 = __dbg_object_init returned
 *   0x45 = chThdObjectInit (main thread) returned
 *   0x46 = REG_INSERT done, state=CURRENT set
 *   0x47 = idle stack filled, about to chThdSpawnRunningI
 *   0x48 = chThdSpawnRunningI returned (function about to return)
 */
volatile uint32_t c1_boot_stage = 0xDEAD0000U;

/*
 * Override the weak __c1_cpu_init stub so we can mark stage 1.
 * Called from _crt0_c1_entry right after MSP/PSP/VTOR/FPU init,
 * before CONTROL switches to PSP.
 */
void __c1_cpu_init(void) {
    c1_boot_stage = 1U;
}

/*
 * Override the weak __c1_late_init stub so we can mark stage 2.
 * Called from _crt0_c1_entry after CONTROL=PSP and stack fill,
 * immediately before bl c1_main.
 */
void __c1_late_init(void) {
    c1_boot_stage = 2U;
}

/**
 * Core 1 entry point — called from _crt0_c1_entry after stack/FPU init.
 */
void c1_main(void) {

    c1_boot_stage = 3U;

    /*
     * Wait for core 0 to finish chSysInit() so the global scheduler
     * structures are ready before we touch them.
     */
    chSysWaitSystemState(ch_sys_running);

    c1_boot_stage = 4U;

    /*
     * Attach this core to the ChibiOS kernel.  After this call the current
     * execution context becomes core1's main (idle) thread.
     *
     * chInstanceObjectInit internally modifies the global thread registry
     * (ch_system.reglist) without the SIO spinlock.  The race with core0's
     * chThdCreateStatic is handled inside chinstances.c by briefly
     * disabling all IRQs (cpsid) and acquiring the spinlock around each
     * registry insertion.  See the SMP_REG_LOCK/UNLOCK macros there.
     */
    chInstanceObjectInit(&ch1, &ch_core1_cfg);

    c1_boot_stage = 0x4AU;  /* chInstanceObjectInit returned cleanly */

    /*
     * chInstanceObjectInit leaves core1 with BASEPRI=16 and the SIO spinlock
     * FREE (released by SMP_REG_UNLOCK at the end of the last critical
     * section).  We must NOT call chSysUnlock() here because port_unlock() in
     * SMP mode calls port_spinlock_release() BEFORE setting BASEPRI=0.  If the
     * spinlock happens to be held by core0 at that instant, port_spinlock_release()
     * silently releases it from under core0, corrupting mutual exclusion and
     * crashing the scheduler.
     *
     * Instead, just lower BASEPRI directly.  The spinlock is already free —
     * no release needed.
     */
    c1_boot_stage = 0x4BU;  /* about to lower BASEPRI to 0 */
    __set_BASEPRI(0U);       /* BASEPRI=0: core1 IRQs now fully live */

    c1_boot_stage = 0x4CU;  /* BASEPRI lowered, IRQs fully live */

    /*
     * Idle loop.  Real work on core1 is performed by threads created with
     * thread_create_alloc_on_core(..., &ch1) from Scheduler.cpp.
     * This thread runs at IDLEPRIO and WFEs when nothing else is ready.
     */
    while (true) {
        c1_boot_stage = 0x4DU;  /* idle loop body (overwritten every iteration) */
        port_wait_for_interrupt();
    }
}

#endif /* CH_CFG_SMP_MODE && PORT_CORES_NUMBER > 1 */
