language: cpp
sudo: false

dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - build-essential
      - gawk
      - genromfs
      - libc6-i386
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-dev
      - zlib1g-dev
      - gdb
      - cmake
      - cmake-data
      - clang-7
      - llvm-7

cache:
  ccache: false
  directories:
    - $HOME/opt

before_install:
  - echo 0 | sudo dd of=/proc/sys/kernel/yama/ptrace_scope
  - Tools/scripts/configure-ci.sh
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export CI_CRON_JOB=1 ; fi

script:
  - Tools/scripts/build_ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5e0b55e353e53945b4b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

compiler:
  - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI="
    - AUTOTEST_UPLOAD=true  # Upload logs of failed tests to ArduPilot server; requires authentication

matrix:
  fast_finish: true
  include:
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.PIDTuning"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ArmFeatures"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SetHome"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ConfigErrorLoop"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.CPUFailsafe"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Parameters"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.LoggerDocumentation"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GetCapabilities"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.NavDelayTakeoffAbsTime"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.NavDelayAbsTime"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.NavDelay"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GuidedSubModeChange"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.LoiterToAlt"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.PayLoadPlaceMission"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.PrecisionLoiterCompanion"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.PrecisionLandingSITL"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SetModesViaModeSwitch"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SetModesViaAuxSwitch"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AuxSwitchOptions"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AutoTune"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ThrowMode"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.BrakeMode"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.RecordThenPlayMission"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ThrottleFailsafe"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GCSFailsafe"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.BatteryFailsafe"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.StabilityPatch"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AC_Avoidance_Proximity"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AC_Avoidance_Fence"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AC_Avoidance_Beacon"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.HorizontalFence"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.HorizontalAvoidFence"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.MaxAltFence"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GPSGlitchLoiter"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GPSGlitchAuto"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ModeAltHold"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ModeLoiter"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SimpleMode"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SuperSimpleCircle"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.LogDownLoad"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.MotorVibration"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ModeCircle"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.OpticalFlowLimits"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.MotorFail"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Flip"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.CopterMission"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.DynamicNotches"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GyroFFT"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.FixedYawCalibration"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.GyroFFTHarmonic"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.LogDownLoad"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SplineLastWaypoint"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Gripper"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.TestGripperMission"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.VisionPosition"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.BeaconPosition"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.RTLSpeed"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Mount"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Button"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.RangeFinder"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.SurfaceTracking"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.Parachute"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ParameterChecks"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ManualThrottleModeChange"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.MANUAL_CONTROL"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ZigZag"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.PosHoldTakeOff"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.FOLLOW"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.OnboardCompassCalibration"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.RangeFinderDrivers"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.ParameterValidation"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.AltTypes"
    - if: type != cron
      compiler: "gcc"
      env: CI_BUILD_TARGET="Copter-build.Copter-test.CopterOne.LogDownLoad"




