#!/bin/bash -x

# must do this once first:
# ./Tools/scripts/esp32_get_idf.sh

cd /home/buzz2/ardupilot
unset LDFLAGS

#pip install pymavlink

mkdir -p build2/esp32s3empty/libraries/GCS_MAVLink/include/mavlink/v2.0
# needs mavgen.py in path
python3 `which mavgen.py` --lang C --wire-protocol 2.0 --no-validate -o build2/esp32s3empty/libraries/GCS_MAVLink/include/mavlink/v2.0 modules/mavlink/message_definitions/v1.0/all.xml


# auto-gen the cmake file for the 'libraries' folder
echo "cmake libs build output missing. updating: ./libraries/libs.short.txt.cmake"
cd libraries
./libraries.cmake.generator.sh
cd ..


if [ ! -f "./modules/esp_idf/export.sh" ]; then
    ./Tools/scripts/esp32_get_idf.sh
    ./modules/esp_idf/install.sh
fi

if [  -f "./modules/esp_idf/export.sh" ]; then
   source ./modules/esp_idf/export.sh
fi

rm CMakeCache.txt


#inspired by https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/idf_as_lib/
export IDF_CCACHE_ENABLE=1
export BUILDDIR='build2'
export BOARD_NAME='esp32s3empty'
export VEHICLETYPE='ArduPlane'
export TARGET=esp32s3
echo "#!/bin/bash -x" > ./cmake.last.env.bin
echo "# autogenerated by cmake configure" >> ./cmake.last.env.bin
echo "export BUILDDIR=$BUILDDIR" >> ./cmake.last.env.bin
echo "export BOARD_NAME=$BOARD_NAME" >> ./cmake.last.env.bin
echo "export VEHICLETYPE=$VEHICLETYPE" >> ./cmake.last.env.bin
echo "export TARGET=$TARGET" >> ./cmake.last.env.bin

#rm -rf $BUILDDIR
cd $BUILDDIR
# u could also cmake  .. -DBUILDDIR=$BUILDDIR -DBOARD_NAME=$BOARD_NAME -DVEHICLETYPE=$VEHICLETYPE -DTARGET=${TARGET}
cmake ..
cd ..

echo "Please now run ./cmake.build.sh to      build the project."
echo "   OR      run ./cmake.build.flash.sh   to build and attempt to flash the connected board"

#tips:
#   'idf.py xxx' doesnt seem to work in the project root, but 'make xxx' in the build2 directory does similar.. eg:
#
#   cd build2 ; make
#
#   cd build2 ; make flash
# 
#   cd build2 ; make monitor
#
#   cd build2 ; make erase_flash
#
#   u can interrogate your specific board to find how much flash it got with:
#     'esptool.py flash_id'
#
# upload via UART labeled cable right-now, its slower, but autodetect finds it